In [5]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [7]:
# import Bechdel_test CSV file and convert to pandas Dataframe
bechdel_csv = "./Datasets/movies.csv"
bechdel_df_1 = pd.read_csv(bechdel_csv)
bechdel_df_1.head()

,year,imdb,title,test,clean_test,binary,budget,domgross,intgross,code,budget_2013$,domgross_2013$,intgross_2013$,period code,decade code
0,2013,tt1711425,21 &amp; Over,notalk,notalk,FAIL,13000000,25682380.0,42195766.0,2013FAIL,13000000,25682380.0,42195766.0,1.0,1.0
1,2012,tt1343727,Dredd 3D,ok-disagree,ok,PASS,45000000,13414714.0,40868994.0,2012PASS,45658735,13611086.0,41467257.0,1.0,1.0
2,2013,tt2024544,12 Years a Slave,notalk-disagree,notalk,FAIL,20000000,53107035.0,158607035.0,2013FAIL,20000000,53107035.0,158607035.0,1.0,1.0
3,2013,tt1272878,2 Guns,notalk,notalk,FAIL,61000000,75612460.0,132493015.0,2013FAIL,61000000,75612460.0,132493015.0,1.0,1.0
4,2013,tt0453562,42,men,men,FAIL,40000000,95020213.0,95020213.0,2013FAIL,40000000,95020213.0,95020213.0,1.0,1.0

In [8]:
# Drop unecessary columns (test, clean_test, budget, domgross, intgross, code, period code, decade code)
bechdel_df_2 = bechdel_df_1[['year', 'imdb', 'title', 'binary', 'budget_2013$', 'domgross_2013$', 'intgross_2013$']]
bechdel_df_2.head()

,year,imdb,title,binary,budget_2013$,domgross_2013$,intgross_2013$
0,2013,tt1711425,21 &amp; Over,FAIL,13000000,25682380.0,42195766.0
1,2012,tt1343727,Dredd 3D,PASS,45658735,13611086.0,41467257.0
2,2013,tt2024544,12 Years a Slave,FAIL,20000000,53107035.0,158607035.0
3,2013,tt1272878,2 Guns,FAIL,61000000,75612460.0,132493015.0
4,2013,tt0453562,42,FAIL,40000000,95020213.0,95020213.0

In [9]:
# Drop Nan values
bechdel_df_2.dropna()

,year,imdb,title,binary,budget_2013$,domgross_2013$,intgross_2013$
0,2013,tt1711425,21 &amp; Over,FAIL,13000000,2.568238e+07,4.219577e+07
1,2012,tt1343727,Dredd 3D,PASS,45658735,1.361109e+07,4.146726e+07
2,2013,tt2024544,12 Years a Slave,FAIL,20000000,5.310704e+07,1.586070e+08
3,2013,tt1272878,2 Guns,FAIL,61000000,7.561246e+07,1.324930e+08
4,2013,tt0453562,42,FAIL,40000000,9.502021e+07,9.502021e+07
5,2013,tt1335975,47 Ronin,FAIL,225000000,3.836248e+07,1.458038e+08
6,2013,tt1606378,A Good Day to Die Hard,FAIL,92000000,6.734920e+07,3.042492e+08
7,2013,tt2194499,About Time,PASS,12000000,1.532392e+07,8.732475e+07
8,2013,tt1814621,Admission,PASS,13000000,1.800732e+07,1.800732e+07
9,2013,tt1815862,After Earth,FAIL,130000000,6.052210e+07,2.443732e+08
10,2013,tt1800241,American Hustle,PASS,40000000,1.484309e+08,2.494849e+08
11,2013,tt1322269,August: Osage County,PASS,25000000,3.730487e+07,5.030487e+07
12,2013,tt1559547,Beautiful Creatures,PASS,50000000,1.945214e+07,5.594067e+07
13,2013,tt2334873,Blue Jasmine,PASS,18000000,3.334583e+07,6.844783e+07
14,2013,tt1535109,Captain Phillips,FAIL,55000000,1.071364e+08,2.187436e+08
15,2013,tt1939659,Carrie,PASS,30000000,3.526662e+07,8.500166e+07
16,2013,tt1985966,Cloudy with a Chance of Meatballs 2,FAIL,78000000,1.196403e+08,2.717254e+08
17,2013,tt1690953,Despicable Me 2,PASS,76000000,3.680654e+08,9.707660e+08
18,2013,tt2229499,Don Jon,FAIL,5500000,2.447770e+07,2.637770e+07
19,2013,tt1535108,Elysium,PASS,120000000,9.305012e+07,2.861921e+08
20,2013,tt1731141,Ender&#39;s Game,FAIL,110000000,6.173719e+07,8.973719e+07
21,2013,tt0848537,Epic,PASS,100000000,1.075187e+08,2.684187e+08
22,2013,tt0765446,Escape from Planet Earth,PASS,40000000,5.701298e+07,6.645481e+07
23,2013,tt1211956,Escape Plan,FAIL,70000000,2.521310e+07,1.038131e+08
24,2013,tt1288558,Evil Dead,PASS,17000000,5.423986e+07,9.740205e+07
25,2013,tt1905041,Fast and Furious 6,PASS,160000000,2.386798e+08,7.881281e+08
26,2013,tt2294629,Frozen,PASS,150000000,3.930501e+08,1.004550e+09
27,2013,tt1583421,G.I. Joe: Retaliation,PASS,140000000,1.225231e+08,3.719231e+08
28,2013,tt1321870,Gangster Squad,FAIL,60000000,4.600090e+07,1.041009e+08
29,2013,tt2425486,Gloria,PASS,30000000,4.167493e+06,4.967493e+06
...,...,...,...,...,...,...,...
1763,1976,tt0074958,Network,PASS,15548943,9.693488e+07,9.693488e+07
1764,1976,tt0075148,Rocky,FAIL,4091827,4.797060e+08,9.206611e+08
1765,1976,tt0075222,Silent Movie,FAIL,18004040,1.479019e+08,1.479019e+08
1766,1976,tt0075249,Sparkle,PASS,40918272,9.983023e+07,1.009058e+08
1767,1976,tt0075314,Taxi Driver,FAIL,4091827,1.156456e+08,1.156456e+08
1768,1975,tt0072684,Barry Lyndon,FAIL,47609104,8.656201e+07,8.656201e+07
1769,1975,tt0073195,Jaws,FAIL,51937204,1.125306e+09,2.037237e+09
1770,1975,tt0071853,Monty Python and the Holy Grail,FAIL,1731240,1.483541e+07,2.176579e+07
1771,1975,tt0073486,One Flew Over the Cuckoo&#39;s Nest,FAIL,19043641,4.716819e+08,4.716819e+08
1772,1975,tt0073629,The Rocky Horror Picture Show,FAIL,5193720,6.053992e+08,6.053992e+08
1773,1974,tt0071222,Black Christmas,PASS,42513535,7.669318e+07,7.669318e+07
1774,1974,tt0071230,Blazing Saddles,FAIL,12281688,5.644853e+08,5.644853e+08
1775,1974,tt0071360,The Conversation,FAIL,7557962,2.087887e+07,2.087887e+07
1776,1974,tt0071562,The Godfather: Part II,PASS,61408439,2.706695e+08,2.706695e+08
1777,1974,tt0072271,The Texas Chain Saw Massacre,FAIL,661322,1.255209e+08,1.255209e+08
1778,1974,tt0072308,The Towering Inferno,FAIL,661322,1.255209e+08,1.255209e+08
1779,1974,tt0072431,Young Frankenstein,FAIL,13226433,4.076576e+08,4.076576e+08
1780,1973,tt0069704,American Graffiti,FAIL,4074506,6.030478e+08,7.341452e+08
1781,1973,tt0068699,High Plains Drifter,FAIL,82329139,8.232914e+07,8.232914e+07
1782,1973,tt0070707,Sleeper,FAIL,10487788,9.619782e+07,9.619782e+07
1783,1973,tt0070047,The Exorcist,PASS,62926730,1.074306e+09,2.111900e+09
1784,1973,tt0070735,The Sting,FAIL,28841418,8.370111e+08,8.370111e+08
1786,1972,tt0069089,Pink Flamingos,PASS,66866,2.305762e+06,2.305762e+06
1787,1972,tt0068646,The Godfather,FAIL,39004975,7.520516e+08,1.496119e+09
1788,1971,tt0067065,Escape from the Planet of the Apes,FAIL,14386286,7.078052e+07,7.078052e+07
1789,1971,tt0067741,Shaft,FAIL,305063707,4.047027e+08,6.168270e+08
1790,1971,tt0067800,Straw Dogs,FAIL,143862856,5.941214e+07,6.476027e+07
1791,1971,tt0067116,The French Connection,FAIL,12659931,2.368487e+08,2.368487e+08
1792,1971,tt0067992,Willy Wonka &amp; the Chocolate Factory,FAIL,17263543,2.301806e+07,2.301806e+07
1793,1970,tt0065466,Beyond the Valley of the Dolls,PASS,5997631,5.397868e+07,5.397868e+07

In [ ]:
# Create Engine and connection to Database
engine = create_engine('postgres://postgres:PASSWORD@localhost:5432/Bechdel_Test')
conn = engine.connect()

In [ ]:
# Verify tables
engine.table_names()

In [ ]:
# Use pandas to load bechdel test csv into converted DataFrame into database
clean_bechdel_test_df.to_sql(name='bechdel_test', conn=engine, if_exists='append', index=False)

In [ ]:
# Confirm data has been added by querying table
pd.read_sql_query('select * from bechdel_test', conn=engine).head()

In [ ]:
## Run sample queries